framework:
    messenger:
        failure_transport: manager.failed
        transports:
            marvin.to.manager:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: marvin.to.manager
                        type: direct
                        default_publish_routing_key: manager.to.marvin.response
                    queues:
                        marvin.to.manager.request:
                            binding_keys:
                                - marvin.to.manager.request
            manager.failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: manager.failed
                    queues:
                        manager.failed.messages: ~

        routing:
            EnderLab\MarvinManagerBundle\Messenger\ManagerResponseMessageInterface: marvin.to.manager

when@test:
   framework:
       messenger:
           transports:
               # replace with your transport name here (e.g., my_transport: 'in-memory://')
               # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
               marvin.to.manager: 'in-memory://'
               manager.failed.: 'in-memory://'
